language: node_js

node_js:
  - "9.5.0"

cache:
  directories:
    - node_modules

script:
  - npm install
  - npm run prettier:check

after_success:
  - now --target staging
  - npm run lh -- --pwa=100 --perf=96 --seo=100 --a11y=90 --bp=90 https://spindlewtf.remi.now.sh
